### ISSUE TITLE
Testing prompt_toolkit (all python, no native dependencies)

### ISSUE THREAD

**Issue by apatrida** [oracle/graalpython#128]
I wanted to try a few Python libraries that have all-Python dependencies.  Prompt Toolkit being one.

```text
prompt_toolkit==3.0.4
pygments==2.6.1
wcwidth==0.1.8
```

I installed these manually into the GraalVM Python using `setup.py` and when running their basic examples I end up with: `TypeError: 'type' object is not subscriptable`

Is this something they are doing that is unsafe, or likely a problem with GraalPython?  Is it something you would like to look into, or since they are "unsupported libraries" I should wait to give more info?

Steps to reproduce:

- install those dependencies above by downloading then and running setup.py via graalpython
- pull the code of python-prompt-toolkit
- go to the samples dir `python-prompt-toolkit/examples/print-text` 
- run `graalpython -m ansi.py`

hit error:

```text
❯ graalpython -m ansi.py      
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "<string>", line 1, in <module '<string>'>
  File "/Users/jminard/.sdkman/candidates/java/20.0.0.r11-grl/languages/python/lib-python/3/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/jminard/.sdkman/candidates/java/20.0.0.r11-grl/languages/python/lib-python/3/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/jminard/DEV/OSS/python/python-prompt-toolkit/examples/print-text/ansi.py", line 8, in <module 'ansi.py'>
    from prompt_toolkit import print_formatted_text
  File "/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/__init__.py", line 16, in <module '/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/__init__.py'>
    from .application import Application
  File "/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/application/__init__.py", line 1, in <module '/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/application/__init__.py'>
    from .application import Application
  File "/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/application/application.py", line 39, in <module '/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/application/application.py'>
    from prompt_toolkit.buffer import Buffer
  File "/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/buffer.py", line 28, in <module '/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/buffer.py'>
    from .application.current import get_app
  File "/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/application/current.py", line 69, in <module '/Users/jminard/.local/lib/python3.7/site-packages/prompt_toolkit-3.0.4-py3.7.egg/prompt_toolkit/application/current.py'>
    _current_app_session: ContextVar["AppSession"] = ContextVar(
TypeError: 'type' object is not subscriptable
```

**Comment by timfel** [comment]
This is likely a missing feature or bug on our side. We will check this out

**Comment by apatrida** [comment]
thanks Tim.  If you need additional information, please let me know.

**Comment by msimacek** [comment]
Hi, I was looking at the problem and I can fix the type error easily. However, that's not enough to make `prompt_toolkit` work as it then crashes because it uses pyexpat XML parser (via minidom), which we haven't implemented yet. I think we should just import the pyexpat C code from CPython, but I'll need to check how doable it is.

**Comment by msimacek** [comment]
We have added pyexpat module and the provided example now works. Hovewer, not all of `prompt_toolkit` works yet, I tried to run its tests and here's the output (just so you know which parts you can expect to work):
```
tests/test_async_generator.py F                                                                               [  0%]
tests/test_buffer.py .........                                                                                [  6%]
tests/test_cli.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                                                          [ 30%]
tests/test_completion.py ..................                                                                   [ 42%]
tests/test_document.py ...........                                                                            [ 50%]
tests/test_filter.py ......                                                                                   [ 54%]
tests/test_formatted_text.py .............                                                                    [ 63%]
tests/test_history.py FFFF                                                                                    [ 66%]
tests/test_inputstream.py ...........                                                                         [ 73%]
tests/test_key_binding.py ......                                                                              [ 77%]
tests/test_layout.py ..                                                                                       [ 79%]
tests/test_print_formatted_text.py ....                                                                       [ 82%]
tests/test_regular_languages.py ....                                                                          [ 84%]
tests/test_shortcuts.py .F                                                                                    [ 86%]
tests/test_style.py .....                                                                                     [ 89%]
tests/test_style_transformation.py .                                                                          [ 90%]
tests/test_utils.py .                                                                                         [ 91%]
tests/test_vt100_output.py .                                                                                  [ 91%]
tests/test_widgets.py ..                                                                                      [ 93%]
tests/test_yank_nth_arg.py ..........                                                                         [100%]
```

All the failures seem to be caused by our lack of support for async event loop, which is currently being worked on.

**Comment by msimacek** [comment]
I tried `prompt_toolkit`'s tests and we now pass them all
