### ISSUE TITLE
Issue with used RAM by GraalVM +Python

### ISSUE THREAD

**Issue by lvca** [oracle/graalpython#146]
Hi guys,
I've replaced my AdaptJDK11 with GraalVM + Python, but my application can't run with 6GB of max heap it was running before. I tried with 8GB but I've got OOM. This is the stack trace:

```
Caused by: org.graalvm.polyglot.PolyglotException: java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
at java.base/java.lang.Thread.start0(Native Method)
at java.base/java.lang.Thread.start(Thread.java:803)
at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:680)
at com.oracle.graal.python.runtime.AsyncHandler.registerAction(AsyncHandler.java:192)
at com.oracle.graal.python.runtime.PythonContext.registerAsyncAction(PythonContext.java:766)
at com.oracle.graal.python.builtins.modules.WeakRefModuleBuiltins.postInitialize(WeakRefModuleBuiltins.java:112)
at com.oracle.graal.python.builtins.Python3Core.postInitialize(Python3Core.java:493)
at com.oracle.graal.python.runtime.PythonContext.initialize(PythonContext.java:390)
at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:210)
at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:92)
at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:2945)
at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:230)
at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:550)
at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:686)
at org.graalvm.sdk/org.graalvm.polyglot.Context.getBindings(Context.java:408)
```

Do you guys know how can I control the RAM usage?

Also, what's the reason why the Python implementation creates threads at run-time?

**Comment by timfel** [comment]
We haven't spent any time so far working on the footprint of GraalVM's Python implementation, so very large heaps are currently (unfortunately) expected.

We need to create threads for signal handlers and weak reference collection. The Python semantics dictate that the handlers are executed on the main thread, but Java delivers them on separate threads, so we need handler threads that transfer relevant state.

**Comment by lvca** [comment]
@timfel what about using a thread pool? I see threads are created non-stop during the execution of the python scripts.

This affects performance and, RAM. Could you please point the code that is responsible for that? I'd like to see if I can help.

Thanks

**Comment by lvca** [comment]
I'm monitoring the JVM and I see the thread number is growing of 10 threads per execution. Is there any special method I should call to free the resources? I guess something remains in RAM even after GraalVM engine is collected.

**Comment by timfel** [comment]
We are using a pool: https://github.com/graalvm/graalpython/blob/master/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/AsyncHandler.java#L130
It's possible we're not shutting it down correctly when the context is discarded

**Comment by lvca** [comment]
Why you guys set a timer for the async event that is invoked every 15ms?

Can't you manage the async operation with CountDownLatch or simple Object.wait/notify instead?

executorService.scheduleWithFixedDelay(new AsyncRunnable(actionSupplier), ASYNC_ACTION_DELAY, ASYNC_ACTION_DELAY, TimeUnit.MILLISECONDS);

**Comment by timfel** [comment]
Because the handlers need to run (time-based) periodically. These async actions will be used for thread switching as well, for example (Python semantics dictate we'll have a GIL at least most of the time, so time-based unlocking and thread switching is easiest). Those async actions that do not periodic actions and can suspend on some lock do that (as you can see [here](https://github.com/graalvm/graalpython/blob/5acaa955c1654295d70c1992651fd5c080680364/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/cext/capi/CApiContext.java#L146), [here](https://github.com/graalvm/graalpython/blob/5acaa955c1654295d70c1992651fd5c080680364/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/modules/WeakRefModuleBuiltins.java#L115), and [here](https://github.com/graalvm/graalpython/blob/5acaa955c1654295d70c1992651fd5c080680364/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/modules/SignalModuleBuiltins.java#L109))

**Comment by timfel** [comment]
I just checked, and we are shutting down the executor service: https://github.com/graalvm/graalpython/blob/5acaa955c1654295d70c1992651fd5c080680364/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/AsyncHandler.java#L292

**Comment by msimacek** [comment]
We have fixed several memory leaks, improved memory usage and we are now shutting down threads more aggressively. I believe this issue can be closed. Feel free to reopen if you still observe problems.
