### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'c_long'

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#175]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/ctypeslib.py", line 86, in <module '/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/ctypeslib.py'>
    c_intp = nic._getintp_ctype()
  File "/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/_internal.py", line 228, in _getintp_ctype
    val = ctypes.c_long
AttributeError: module 'ctypes' has no attribute 'c_long'
```

**Comment by msimacek** [comment]
Added in b8a3160231a0aaba800a6bafd5d15e95fe922752
