### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'c_byte'

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#176]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/ctypeslib.py", line 371, in <module '/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/ctypeslib.py'>
    _scalar_type_map = _get_scalar_type_map()
  File "/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/ctypeslib.py", line 363, in _get_scalar_type_map
    ct.c_byte, ct.c_short, ct.c_int, ct.c_long, ct.c_longlong,
AttributeError: module 'ctypes' has no attribute 'c_byte'
```

**Comment by msimacek** [comment]
Added in b8a3160231a0aaba800a6bafd5d15e95fe922752
