### ISSUE TITLE
Cannot build on system with Python 2.7

### ISSUE THREAD

**Issue by Martynas-P** [oracle/graalpython#198]
When I tried to build GraalPython on a system with Python 2.7, I got an error that it could not import `pathlib` module. 

```
$ mx build
Traceback (most recent call last):
  File "/home/martynas/projects/mx/mx.py", line 17349, in <module>
    main()
  File "/home/martynas/projects/mx/mx.py", line 17232, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home/martynas/projects/mx/mx.py", line 3527, in _discover_suites
    _register_visit(primary)
  File "/home/martynas/projects/mx/mx.py", line 3525, in _register_visit
    s._load()
  File "/home/martynas/projects/mx/mx.py", line 1620, in _load
    self._load_extensions()
  File "/home/martynas/projects/mx/mx.py", line 2042, in _load_extensions
    mod = __import__(extensionsName)
  File "/home/martynas/projects/graalpython/mx.graalpython/mx_graalpython.py", line 32, in <module>
    import pathlib
ImportError: No module named pathlib
```

The reason for this is that commit f30e9699a7f7428256f0e738ebc1aab1cd709689 added an import of `pathlib` which exists only Python 3, but not in Python 2.

If the commit is reverted, then the build runs.

I assume that Python 2 is still supported, since I can see the scripts doing all sorts of compatibility checks.

**Comment by qunaibit** [comment]
the `mx` tool is phasing out python 2.7 support.
please set `MX_PYTHON_VERSION=3` before executing `mx build` 
or you could add:
```
export MX_PYTHON_VERSION=3
```
to your `~/.bashrc` or `~/.zshrc`

**Comment by Martynas-P** [comment]
Thanks, that worked.

**Comment by timfel** [comment]
> I assume that Python 2 is still supported, since I can see the scripts doing all sorts of compatibility checks.

The checks are simply leftover from when we did support Python 2. It is no longer supported.
