### ISSUE TITLE
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by josevnz** [oracle/graalpython#203]
# Environment
```
(wpscan) [josevnz@macmini2 ~]$ uname -a
Linux macmini2 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(wpscan) [josevnz@macmini2 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1959         133        1735           0          91        1707
Swap:          2099         118        1981
(wpscan) [josevnz@macmini2 ~]$ ls
bin  Desktop  Downloads  graalvm-ce-java11-21.0.0.2   virtualenv
(wpscan) [josevnz@macmini2 ~]$ graalvm-ce-java11-21.0.0.2/bin/ruby -v
truffleruby 21.0.0.2, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
(wpscan) [josevnz@macmini2 ~]$ graalvm-ce-java11-21.0.0.2/bin/graalpython -v
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[python::PythonCore] FINE: Initial locations:
	Language home: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python
	SysPrefix: 
	BaseSysPrefix: 
	CoreHome: 
	StdLibHome: 
	CAPI: 
[python::PythonCore] FINE: Updated locations:
	Language home: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python
	SysPrefix: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python
	BaseSysPrefix: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python
	CoreHome: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python/lib-graalpython
	StdLibHome: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python/lib-python/3
	Executable: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python/bin/graalpython
	CAPI: /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python/lib-graalpython
[python::PythonCore] FINE: Using preinitialized context.
[python::NativeLibrary] FINE: Loading native library libzsupport from path /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python/lib-graalpython/libzsupport.graalpython-38-native-x86_64-linux.so 
Python 3.8.5 (Mon Feb 08 20:03:06 UTC 2021)
[Graal, GraalVM CE, Java 11.0.10] on linux

```

# Error
This happens from a script that works just fine with regular Python3 on Linux
```
(wpscan2) [josevnz@macmini2 ~]$ time /home/josevnz/graalvm-ce-java11-21.0.0.2/languages/python/bin/graalpython bin/send_telegram_mesg.py This is a test
Traceback (most recent call last):
  File "/home/josevnz/.local/lib/python3.8/site-packages/urllib3-1.25.6-py3.8.egg/urllib3/connectionpool.py", line 654, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/home/josevnz/.local/lib/python3.8/site-packages/urllib3-1.25.6-py3.8.egg/urllib3/connectionpool.py", line 274, in _get_conn
    return conn or self._new_conn()
  File "/home/josevnz/.local/lib/python3.8/site-packages/urllib3-1.25.6-py3.8.egg/urllib3/connectionpool.py", line 963, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josevnz/.local/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/josevnz/.local/lib/python3.8/site-packages/urllib3-1.25.6-py3.8.egg/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/josevnz/.local/lib/python3.8/site-packages/urllib3-1.25.6-py3.8.egg/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /boXXXXX0/sendMessage?chat_id=%40kodegeek_messages&parse_mode=MarkdownV2&disable_web_page_preview=True&disable_notification=True&allow_sending_without_reply=True&text=This+is+a+test (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josevnz/bin/send_telegram_mesg.py", line 49, in <module 'send_telegram_mesg.py'>
    result = sendMessage(" ".join(sys.argv[1:]))
  File "/home/josevnz/bin/send_telegram_mesg.py", line 45, in sendMessage
    response = requests.get(url, params=payload)
  File "/home/josevnz/.local/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/josevnz/.local/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/josevnz/.local/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/josevnz/.local/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/josevnz/.local/lib/python3.8/site-packages/requests-2.22.0-py3.8.egg/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXX/sendMessage?chat_id=%40XXX&parse_mode=MarkdownV2&disable_web_page_preview=True&disable_notification=True&allow_sending_without_reply=True&text=This+is+a+test (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```
# Script code (removed private bits)
```
!/usr/bin/env python3
"""
Wrapper for Telegram messages
Author: Jose Vicente Nunez
"""
import sys
import requests
BOT_CONFIG = {
    "chat_id": "@XXXXX",
    "name": "XXXX",
    "username": "XXXX_bot",
    "api_key": "XXXX",
    "base_url": "https://api.telegram.org",
    "disable_web_page_preview": True,
    "parse_mode": "MarkdownV2",
    "disable_notification": True,
    "allow_sending_without_reply": True
}

def escape_chars(message):
    return message\
            .replace(".", "\\.")\
            .replace("*", "\\*")\
            .replace("[", "\\[")\
            .replace("]", "\\]")\
            .replace("(", "\\(")\
            .replace(")", "\\)")\
            .replace("-", "\\-")\
            .replace("`", "\\`")

def sendMessage(message:str):
    """
    :param str message
    """
    payload = {
                "chat_id": BOT_CONFIG["chat_id"],
                "parse_mode": BOT_CONFIG["parse_mode"],
                "disable_web_page_preview": BOT_CONFIG["disable_web_page_preview"],
                "parse_mode": BOT_CONFIG["parse_mode"],
                "disable_notification": BOT_CONFIG["disable_notification"],
                "allow_sending_without_reply": BOT_CONFIG["allow_sending_without_reply"],
                "text": escape_chars(message),
            }
    url = "{base_url}/bot{api_key}/sendMessage".format_map(BOT_CONFIG)
    response = requests.get(url, params=payload)
    return response.json()

if __name__ == "__main__":
    result = sendMessage(" ".join(sys.argv[1:]))
    print("Response: {}".format(result))

```

**Comment by timfel** [comment]
Hi,
you are right, Graalpython does not implement the `_ssl` module so far. However, in the upcoming release and in master we now have `_ssl` implemented using the Java SSL APIs. I have just tried your script and it looks like it will work with the next Graalpython release :)

I suggest we keep this issue open until that release is out.

**Comment by josevnz** [comment]
Those are really good news!. This project looks promising and I would love to see it as a replacement for say, Jython, who is stuck in version 2.7. No problem, I will keep it open and will re-rest as soon new release comes out.

Thanks for your quick response.

--Jose

**Comment by msimacek** [comment]
The new 21.1.0 release contains the new `ssl` module. I believe this issue can be considered fixed.
