### ISSUE TITLE
zipfile execution

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#217]
I'm a bit surprised GraalPython cannot execute zipfile.

```
unzip -l foo.zip
Archive:  foo.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  05-27-2021 11:16   foo/
       13  05-27-2021 11:16   foo/__main__.py
---------                     -------
       13                     2 files
```

CPython can execute this `foo.zip` but not GraalPython. I see
https://github.com/oracle/graalpython/blob/master/graalpython/lib-python/3/runpy.py
so my expectation was GraalPython can execute zipfile.

Am I missing something?

**Comment by msimacek** [comment]
How exactly did you execute it with CPython? I made a zip file structured like yours and CPython couldn't execute it either. It needs the `__main__.py` file to be at the top level archive, then it works with both.

**Comment by oroppas** [comment]
Here's how I executed

**CPython**

```
ryuta@sapporo $ python ./foo.zip/foo
foo
```

**GraalPython**

```
yuta@sapporo $ graalpython ./foo.zip/foo
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
java.nio.file.FileSystemException: foo.zip/foo: Not a directory
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at com.oracle.truffle.polyglot.FileSystems$NIOFileSystem.newByteChannel(FileSystems.java:707)
	at com.oracle.truffle.api.TruffleFile.newByteChannel(TruffleFile.java:786)
	at com.oracle.truffle.api.TruffleFile.readAllBytes(TruffleFile.java:856)
	at com.oracle.truffle.api.source.Source.read(Source.java:1200)
	at com.oracle.truffle.api.source.Source.buildSource(Source.java:1058)
	at com.oracle.truffle.api.source.Source$SourceBuilder.build(Source.java:1574)
	at com.oracle.truffle.api.source.Source$LiteralBuilder.build(Source.java:1734)
	at com.oracle.truffle.polyglot.PolyglotSource.build(PolyglotSource.java:296)
	at org.graalvm.polyglot.Source$Builder.build(Source.java:920)
	at com.oracle.graal.python.shell.GraalPythonMain.evalNonInteractive(GraalPythonMain.java:499)
	at com.oracle.graal.python.shell.GraalPythonMain.launch(GraalPythonMain.java:398)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at com.oracle.graal.python.shell.GraalPythonMain.main(GraalPythonMain.java:62)
```

`foo.zip` archives the folder `foo` containing `__main__.py` which looks like

```python
cat foo/__main__.py

print('foo')
```
