### ISSUE TITLE
HAVE_UNISTD_H value not defined?

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#219]
It appears `HAVE_UNISTD_H` value is not defined in GraalPython.

`find ./graal -name "*.h" -exec grep -H --color "\<HAVE_UNISTD_H" {} ';'`

Truffle and Sulong defines the value to 1

```
graal/sulong/mxbuild/linux-amd64/projects/com.oracle.truffle.llvm.libraries.bitcode.libcxx/include/llvm/Config/config.h:#define HAVE_UNISTD_H 1
graal/sulong/mxbuild/linux-amd64/projects/com.oracle.truffle.llvm.libraries.bitcode.libcxx/amd64/include/llvm/Config/config.h:#define HAVE_UNISTD_H 1
graal/truffle/mxbuild/linux-amd64/src/libffi/libffi-3.3/msvc_build/aarch64/aarch64_include/fficonfig.h:#define HAVE_UNISTD_H 1
graal/truffle/mxbuild/linux-amd64/src/libffi/libffi-build/fficonfig.h:#define HAVE_UNISTD_H 1
```

whereas GraalPython does not define value

```
graal/sdk/mxbuild/linux-amd64/GRAALVM_2337E0D01C_JAVA11/graalvm-2337e0d01c-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_48A0BECCB9_JAVA11/graalvm-48a0beccb9-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_497EF68B50_JAVA11/graalvm-497ef68b50-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_8052F32AFF_JAVA11/graalvm-8052f32aff-java11-21.3.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_845C45B806_JAVA11/graalvm-845c45b806-java11-21.2.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_B95281748D_JAVA11/graalvm-b95281748d-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_04C4632E99_JAVA11_STAGE1/graalvm-04c4632e99-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_16A1B89BB9_JAVA11_STAGE1/graalvm-16a1b89bb9-java11-21.3.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_997DAD3A94_JAVA11_STAGE1/graalvm-997dad3a94-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_BC9983AB10_JAVA11_STAGE1/graalvm-bc9983ab10-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_D60DE30A72_JAVA11_STAGE1/graalvm-d60de30a72-java11-21.1.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/GRAALVM_277A86B804_JAVA11_STAGE1/graalvm-277a86b804-java11-21.2.0-dev/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/PYTHON_INSTALLABLE_SVM_JAVA11/languages/python/include/Python.h:#define HAVE_UNISTD_H
graal/sdk/mxbuild/linux-amd64/PYTHON_STANDALONE_SVM_JAVA11/graalpython-21.3.0-dev-linux-amd64/include/Python.h:#define HAVE_UNISTD_H
```
CPython define `HAVE_UNISTD_H` value in `pyconfig.h` (or `pyconfig-64.h` depending on distribution)

```
grep HAVE_UNISTD_H /usr/include/python3.6m/pyconfig-64.h 
#define HAVE_UNISTD_H 1
```

**Comment by fangerer** [comment]
Hi @oroppas,
we currently don't have a build-time configuration step like CPython. That's why we don't define `HAVE_UNISTD_H`. Since the systems we currently support will most certainly just have it, I think we can just define it.

I would still be interested in the reason why you need it. Did you experience any compilation errors when building C extensions?

**Comment by oroppas** [comment]
Hi @fangerer ,

I encountered the error when I was experimenting with numpy 1.18 and 1.19.
It turns out the recent numpy 1.21.0 doesn't rely on it and I was able to build without any issue!
Of course, it's one thing to build & install and other to be able run.

```
graalpython -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ryuta/packages/graalvm/graalpython/numpy/numpy-1.21.0/numpy/__init__.py", line 150, in <module '__init__.py'>
    from . import core
  File "/home/ryuta/packages/graalvm/graalpython/numpy/numpy-1.21.0/numpy/core/overrides.py", line 7, in <module 'overrides.py'>
    from numpy.core._multiarray_umath import (
RuntimeError: 15
```

Anyway, I don't think we need this for now. 

Do you have a plan to have a configure step in future? It'll be "nice to have" for the sake of completeness.

**Comment by fangerer** [comment]
Hi @oroppas, yes, we have a plan to add a configure step at build-time in future but there is no timeline for it.

**Comment by oroppas** [comment]
@fangerer Sounds good. I'll be happy to volunteer to help. Please let me know when the time comes.
