### ISSUE TITLE
pip-21.2.1 under venv fails

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#236]
I wonder if this is known issue.

I can successfully install, say `pyrsistent` under `venv` with associated `pip`:

```
ryuta@oroppas ~
./local/graalpython/bin/graalpython -m pip install pyrsistent
Processing ./.cache/pip/wheels/d9/d1/94/8c9af2be5e7dba996dcd7c2eee9635f947d02e89c05ebc5fb4/pyrsistent-0.18.0-py3-none-any.whl
Looking for Graal Python patches for pyrsistent
Installing collected packages: pyrsistent
Looking for Graal Python patches for pyrsistent
Successfully installed pyrsistent-0.18.0
WARNING: You are using pip version 20.1.1; however, version 21.2.1 is available.
You should consider upgrading via the '/home/ryuta/local/graalpython/bin/graalpython -m pip install --upgrade pip' command.
(graalpython) 
```

Now if I update `pip` as `WARNING` suggests

```
ryuta@oroppas ~
./local/graalpython/bin/graalpython -m pip install --upgrade pip
Collecting pip
  WARNING: Cache entry deserialization failed, entry ignored
  Downloading pip-21.2.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 2.1 MB/s 
Looking for Graal Python patches for pip
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Looking for Graal Python patches for pip
Successfully installed pip-21.2.1
(graalpython)
```

then installing `pyrsistent` fails:

```
ryuta@oroppas ~
./local/graalpython/bin/graalpython -m pip install pyrsistent
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 300, in run
    resolver = self.make_resolver(
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 306, in make_resolver
    import pip._internal.resolution.resolvelib.resolver
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 17, in <module 'resolver.py'>
    from pip._internal.resolution.resolvelib.provider import PipProvider
  File "/tmp/pip-unpacked-wheel-2awrr5fx/pip/_internal/resolution/resolvelib/provider.py", line 1
SyntaxError: invalid syntax
(graalpython)
```

It's not just `pyrsistent` but other package such as `wheel` as well

```
ryuta@oroppas ~
./local/graalpython/bin/graalpython -m pip install wheel
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 300, in run
    resolver = self.make_resolver(
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 306, in make_resolver
    import pip._internal.resolution.resolvelib.resolver
  File "/home/ryuta/local/graalpython/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 17, in <module 'resolver.py'>
    from pip._internal.resolution.resolvelib.provider import PipProvider
  File "/tmp/pip-unpacked-wheel-2awrr5fx/pip/_internal/resolution/resolvelib/provider.py", line 1
SyntaxError: invalid syntax
(graalpython)
```

**Comment by msimacek** [comment]
There was a problem in deserializing complex `for` comprehensions from `pyc` files. I have fix ready
