### ISSUE TITLE
graalpython - m ginstall with custom index-url

### ISSUE THREAD

**Issue by limanhei** [oracle/graalpython#275]
My dev environment is behind firewall and no proxy can be configured. Would like to see if ginstall can work for custom index-url which pull binaries from custom repository. I am using pip now but hitting issue when pip install scipy.

**Comment by msimacek** [comment]
Hi @limanhei, there are two environment variables that control the index URL, here they are with their defaults for PyPI:
```
GINSTALL_PACKAGE_PATTERN="https://pypi.org/pypi/%s/json"
GINSTALL_PACKAGE_VERSION_PATTERN="https://pypi.org/pypi/%s/%s/json"
```
So if you want to use a custom repository, replace `pypi.org` with your index and set *both* of them.

**Comment by limanhei** [comment]
when I tried to install, it shows "Package not found: 'scipy'", in my repo I only see wheel file and tar ball, there is no json.

**Comment by msimacek** [comment]
We don't support installing from local directories in `ginstall`, just real repostitory servers. What's the issue when installing with `pip`? The difference between using `pip` and `ginstall` is mostly that they pick different versions of packages. I think you should be able to install it with `pip install  numpy==1.16.4 scipy==1.3.1` (that's the versions that `ginstall` would use).

**Comment by paymok** [comment]
hi i work with @limanhei in the team and want to share some finding. 

I have doubt is numpy 1.16.4 compatible with scipy 1.3.1, I checked the scipy 1.3.1 requirements, only numpy 1.14.5 is compatible with non AIX platform. Note that im testing the installation in Ubuntu 20.04.4 LTS.  below is the pyproject.toml requirementi found  in scipy 1.3.1 project.
```
    "numpy==1.13.3; python_version=='3.5' and platform_system!='AIX'",
    "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'",
    "numpy==1.14.5; python_version>='3.7' and platform_system!='AIX'",
    "numpy==1.16.0; python_version=='3.5' and platform_system=='AIX'",
    "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'",
    "numpy==1.16.0; python_version>='3.7' and platform_system=='AIX'", 
```
when I install scipy 1.3.1 with graalpython, pip ignored the numpy 1.16.4 already in the venv, and go ahead installing numpy 1.14.5. evetually the pip install failed when compiling the numpy 1.14.5 due to no patch applied.

**Comment by msimacek** [comment]
We don't support AIX, I think that we just ignored the dependencies. You could make `pip` ignore them too with `--no-dependencies`.

I tried to dig more into `ginstall` and it seems you can make ginstall install from local files after all, the variables then would look like this:
```
export GINSTALL_PACKAGE_PATTERN=file:///path/to/your/repo/%s.zip
export GINSTALL_PACKAGE_VERSION_PATTERN=file:///path/to/your/repo/%s-%s.zip
```
You'll need the zip sources, not binary wheels

**Comment by paymok** [comment]
We are not trying to install into AIX, we are just trying to install scipy in a ubuntu environment. 
I tried again on a new vm just to avoid any proxy firewall hurdles, running ubuntu server 20.04.4 LTS with 8gb memory, 
using following install script, but still no luck on the installation. 

```
export GRAALPY_WORKSPACE=/home/ubuntu/workspace/graealpython
export JAVA_HOME=$GRAALPY_WORKSPACE/tools/graalvm-ce-java11-22.1.0
export PVENV_HOME=$GRAALPY_WORKSPACE/tools/graalvm/pvenv
export PATH=$PVENV_HOME/bin:$JAVA_HOME/bin:$PATH
export PYTHON_EXECUTABLE=$PVENV_HOME/graalpython

mkdir -p $GRAALPY_WORKSPACE/tools
sudo apt install -y patch gcc curl automake gcc g++ subversion python3-dev
sudo apt clean all
cd $GRAALPY_WORKSPACE
curl -SLO "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java11-linux-amd64-22.1.0.tar.gz"
curl -SLO "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/llvm-toolchain-installable-java11-linux-amd64-22.1.0.jar"
curl -SLO "https://github.com/graalvm/graalpython/releases/download/vm-22.1.0/python-installable-svm-java11-linux-amd64-22.1.0.jar"
tar -xf "graalvm-ce-java11-linux-amd64-22.1.0.tar.gz" -C $GRAALPY_WORKSPACE/tools
sudo chmod 777 $GRAALPY_WORKSPACE/tools/graalvm-ce-java11-22.1.0/bin/gu
gu -L install "llvm-toolchain-installable-java11-linux-amd64-22.1.0.jar"
gu -L install "python-installable-svm-java11-linux-amd64-22.1.0.jar"
graalpython -m venv tools/pvenv
source tools/pvenv/bin/activate
pip install numpy==1.16.4
```

On running `pip install scipy==1.3.1` i am getting following error, i also tried the `--no-dependencies` flag, getting the same error.

```
....
 File "/tmp/pip-install-0xm337kd/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
          source = func(extension, build_dir)
        File "/tmp/pip-install-0xm337kd/numpy/numpy/core/setup.py", line 456, in generate_config_h
          rep = check_long_double_representation(config_cmd)
        File "/tmp/pip-install-0xm337kd/numpy/numpy/core/setup_common.py", line 247, in check_long_double_representation
          ltype = long_double_representation(pyod("_configtest"))
        File "/tmp/pip-install-0xm337kd/numpy/numpy/core/setup_common.py", line 391, in long_double_representation
          **raise ValueError("Could not lock sequences (%s)" % saw)**
      **ValueError: Could not lock sequences (None)**
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/ubuntu/workspace/graealpython/tools/pvenv/bin/graalpython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0xm337kd/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0xm337kd/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r61b3u2m/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-nw0dt35z/overlay --compile --install-headers /home/ubuntu/workspace/graealpython/tools/pvenv/include/site/python3.8/numpy Check the logs for full command output.
  WARNING: You are using pip version 20.1.1; however, version 22.2.2 is available.
  You should consider upgrading via the '/home/ubuntu/workspace/graealpython/tools/pvenv/bin/graalpython -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/workspace/graealpython/tools/pvenv/bin/graalpython /home/ubuntu/workspace/graealpython/tools/pvenv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nw0dt35z/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.2' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 22.2.2 is available.
You should consider upgrading via the '/home/ubuntu/workspace/graealpython/tools/pvenv/bin/graalpython -m pip install --upgrade pip' command.
(pvenv) ubuntu@test-ubuntu:~/workspace/graealpython$

```

I tried install scipy through ginstall, installation still not success.

```
(pvenv) ubuntu@test-ubuntu:~/workspace/graealpython$ graalpython -m ginstall install scipy
Installing required dependency: scipy ...
+  curl -L -o /tmp/tmp1c71n_q9/scipy-1.3.1.tar.gz https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.5M  100 22.5M    0     0  10.2M      0  0:00:02  0:00:02 --:--:-- 10.2M
+  tar xzf /tmp/tmp1c71n_q9/scipy-1.3.1.tar.gz -C /tmp/tmp1c71n_q9
+  patch -d /tmp/tmp1c71n_q9/scipy-1.3.1/ -p1 -i /home/ubuntu/workspace/graealpython/tools/graalvm-ce-java11-22.1.0/languages/python/lib-graalpython/patches/scipy/sdist/scipy.patch
patching file scipy/__init__.py
+ cd /tmp/tmp1c71n_q9/scipy-1.3.1 ; /home/ubuntu/workspace/graealpython/tools/pvenv/bin/graalpython setup.py install

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Running from scipy source directory.
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/home/ubuntu/workspace/graealpython/tools/pvenv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/home/ubuntu/workspace/graealpython/tools/pvenv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

openblas_clapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas,lapack not found in ['/home/ubuntu/workspace/graealpython/tools/pvenv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib64
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib64
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib64
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib64
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib64
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /home/ubuntu/workspace/graealpython/tools/pvenv/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib64
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib64
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

/home/ubuntu/workspace/graealpython/tools/pvenv/lib/python3.8/site-packages/numpy/distutils/system_info.py:639: UserWarning:
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
lapack_info:
customize UnixCCompiler
  libraries lapack not found in ['/home/ubuntu/workspace/graealpython/tools/pvenv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
  NOT AVAILABLE

/home/ubuntu/workspace/graealpython/tools/pvenv/lib/python3.8/site-packages/numpy/distutils/system_info.py:639: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
lapack_src_info:
  NOT AVAILABLE

/home/ubuntu/workspace/graealpython/tools/pvenv/lib/python3.8/site-packages/numpy/distutils/system_info.py:639: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
  NOT AVAILABLE

Traceback (most recent call last):
  File "/tmp/tmp1c71n_q9/scipy-1.3.1/setup.py", line 505, in <module 'setup.py'>
    setup_package()
  File "/tmp/tmp1c71n_q9/scipy-1.3.1/setup.py", line 501, in setup_package
    setup(**metadata)
  File "/home/ubuntu/workspace/graealpython/tools/pvenv/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "/tmp/tmp1c71n_q9/scipy-1.3.1/setup.py", line 403, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.

None
(pvenv) ubuntu@test-ubuntu:~/workspace/graealpython$ 
```

**Comment by paymok** [comment]
Hi again, i sorted out the issue finally. it seems the problem is due to the `scipy 1.3.1` is too old and not compatible with the latest `gcc-11` and `gfortran-11`. From `scipy` issue page some suggested to use `gfortran-9` that could solve the problem.  And there are some extra packages required in order to make the `scipy` build success.
```
sudo apt install -y patch gcc-9 gfortran-9 curl automake g++ subversion python3-dev libopenblas-dev liblapack-dev 
```

Also i need to default `gcc` and `gfortran` to use v9 to keep the scipy compile happy.
```
#default to use gfortran 9 as default compiler, this setting is for install scipy 1.3.1
sudo ln -fs /usr/bin/gcc-9 gcc
sudo ln -fs /usr/bin/gcc-ar-9 g-ar
sudo ln -fs /usr/bin/gcc-nm-9 g-nm
sudo ln -fs /usr/bin/gcc-ranlib-9 g-ranlib
sudo ln -fs /usr/bin/gfortran-9 gfortran
```

In the end i need to manually install `wheel` since i skip any requirement install from `scipy`. 
also need to add `--no-build-isolation` and `--no-deps` to avoid `pip` installing a older version of `numpy` which doesn't have patch from `graalpython`

``` 
pip install wheel==0.34.0
pip install numpy==1.16.4
pip install --no-build-isolation --no-deps scipy==1.3.1
```

Below is full list of command to setup the env

```
export GRAALPY_WORKSPACE=/home/ubuntu/workspace/graealpython
export JAVA_HOME=$GRAALPY_WORKSPACE/tools/graalvm-ce-java11-22.1.0
export PVENV_HOME=$GRAALPY_WORKSPACE/tools/graalvm/pvenv
export PATH=$PVENV_HOME/bin:$JAVA_HOME/bin:$PATH
export PYTHON_EXECUTABLE=$PVENV_HOME/graalpython

mkdir -p $GRAALPY_WORKSPACE/tools
sudo apt install -y patch gcc-9 gfortran-9 curl automake g++ subversion python3-dev libopenblas-dev liblapack-dev 
#force to use gfortran 9 as default compiler, this setting is for install scipy 1.3.1
sudo ln -fs /usr/bin/gcc-9 gcc
sudo ln -fs /usr/bin/gcc-ar-9 g-ar
sudo ln -fs /usr/bin/gcc-nm-9 g-nm
sudo ln -fs /usr/bin/gcc-ranlib-9 g-ranlib
sudo ln -fs /usr/bin/gfortran-9 gfortran

sudo apt clean all
cd $GRAALPY_WORKSPACE
curl -SLO "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java11-linux-amd64-22.1.0.tar.gz"
curl -SLO "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/llvm-toolchain-installable-java11-linux-amd64-22.1.0.jar"
curl -SLO "https://github.com/graalvm/graalpython/releases/download/vm-22.1.0/python-installable-svm-java11-linux-amd64-22.1.0.jar"
tar -xf "graalvm-ce-java11-linux-amd64-22.1.0.tar.gz" -C $GRAALPY_WORKSPACE/tools
sudo chmod 777 $GRAALPY_WORKSPACE/tools/graalvm-ce-java11-22.1.0/bin/gu
gu -L install "llvm-toolchain-installable-java11-linux-amd64-22.1.0.jar"
gu -L install "python-installable-svm-java11-linux-amd64-22.1.0.jar"
graalpython -m venv tools/pvenv
cd $GRAALPY_WORKSPACE
source tools/pvenv/bin/activate
pip install wheel==0.34.0
pip install numpy==1.16.4
pip install --no-build-isolation --no-deps scipy==1.3.1

```

**Comment by cosminbasca** [comment]
Hi @paymok ! 

Thanks for your interest in _graalpy_ and in investigating how to get scipy to work with it. As you already observed, support for scipy is limited at this stage. We are working on providing support for installing a newer version of scipy, but there will still be missing native bits that are not yet supported or are simply missing from _graalpy_ at the moment - we are working on filling those gaps! In particular support for _fortran_ is somewhat limited at this stage and it may take a while for it to become comprehensive.

**Comment by msimacek** [comment]
In GraalPy 23.0, we no longer use LLVM for C extension execution by default, so there shouldn't be problems with compiling fortran anymore. We are still working on some missing parts and bugs, but in general, `scipy` should work. Please open a new issue if you run into specific problems.
