### ISSUE TITLE
venv fails to create the virtual environment

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#291]
`venv` starts failing on the main branch:

```
graalpy -m venv ./local/graalpy
We're not using symlinks in a Graal Python venv
Error: Command '['/home/ryuta/local/graalpy/bin/graalpy', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

Is this known issue? What is the best way to diagnose?

**Comment by msimacek** [comment]
We're not aware of any problems there, it works for me locally. To get more details, you can manually run the failed command that it printed

**Comment by oroppas** [comment]
For some reason, the directory `_bundled` and its content `setuptools-47.1.0-py3-none-any.whl` are missing under `sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/ensurepip`

```
graalpy -Im ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/ensurepip/__init__.py", line 216, in _main
    default_pip=args.default_pip,
  File "/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/ensurepip/__init__.py", line 109, in _bootstrap
    whl = pkgutil.get_data(
  File "/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ryuta/packages/vm/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_EBE5D92740_JAVA11/graalvm-ebe5d92740-java11-23.0.0-dev/languages/python/lib-python/3/ensurepip/_bundled/setuptools-47.1.0-py3-none-any.whl'
```

I'll try to do clean-build to see if the issue will be fixed.

**Comment by oroppas** [comment]
Building from scratch didn't fix the issue.

**Comment by msimacek** [comment]
Try to delete all the `mxbuild` directories manually, especially the one in `graal/sdk` and build again. The whole `graalpython/lib-python` directory just gets copied to `mxbuild`, there should be nothing special about the `_bundled` subdirectory. Make sure you didn't delete or change permissions of the files in `graalpython/lib-python` and you have enough space on your partition. If the problem persists, post your whole output of `mx build`.

**Comment by oroppas** [comment]
Fixed by recent update.
