### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'get_asyncgen_hooks'

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#300]
Here's how to replicate the error:

1. `graalpy -m pip install textual`
2. `graalpy -m textual`

and the traceback

```
(graalpy) [ryuta@fedora tmp]$ graalpy -m textual
Traceback (most recent call last):
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    old_agen_hooks = sys.get_asyncgen_hooks()
AttributeError: module 'sys' has no attribute 'get_asyncgen_hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ryuta/packages/graalvm/graalpy/lib/python3.10/site-packages/textual/__main__.py", line 6, in <module>
    app.run()
  File "/home/ryuta/packages/graalvm/graalpy/lib/python3.10/site-packages/textual/app.py", line 873, in run
    asyncio.run(run_app())
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/home/ryuta/packages/graalvm/graalvm/graal/sdk/mxbuild/linux-amd64/GRAALVM_3666026860_JAVA17/graalvm-3666026860-java17-23.0.0-dev/languages/python/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    old_agen_hooks = sys.get_asyncgen_hooks()
AttributeError: module 'sys' has no attribute 'get_asyncgen_hooks'
```

**Comment by msimacek** [comment]
Hi Ryuta, GraalPy doesn't yet have support for asyncio in general. It's currently being worked on

**Comment by oroppas** [comment]
Hi Michael. It's good to know `asyncio` is being worked on!

**Comment by oroppas** [comment]
2494d46 fixed the error.
