### ISSUE TITLE
GraalPython performance is terrible when Pandas is used

### ISSUE THREAD

**Issue by subashatreya** [oracle/graalpython#334]
I installed GraalVM 22.3.1, Python Language, and NumPy and Pandas as described in:
https://www.graalvm.org/latest/reference-manual/python/

Here is my sample test.py

`import pandas as pd
import time
start = time.time() * 1000
data_dict = []
for i in range(100):
    data_dict.append({
            'name': 'User'+str(i),
            'score1': i,
            'score2': i
    })

df = pd.DataFrame(data_dict)
mean = df['score1'].mean()

end = time.time() * 1000

print("Time Taken(ms): " + str(end-start))`

++++

$JAVA_HOME/languages/python/bin/python test.py
Time Taken(ms): 1139.0

If I run the same script with default CPython, then it finishes in under 5ms.

**Comment by subashatreya** [comment]
I tried a slightly different version with a loop.

```
data_dict = []
for i in range(100):
    data_dict.append({
            'name': 'User'+str(i),
            'score1': i,
            'score2': i
    })


for i in range(10):
    start = time.time() * 1000
    df = pd.DataFrame(data_dict)
    mean = df['score1'].mean()
    end = time.time() * 1000
    print("Time Taken(ms): " + str(end-start))
```

Here are the numbers from CPython
Time Taken(ms): 4.468994140625
Time Taken(ms): 0.679443359375
Time Taken(ms): 0.52490234375
Time Taken(ms): 0.4150390625
Time Taken(ms): 0.39501953125
Time Taken(ms): 0.4150390625
Time Taken(ms): 0.385009765625
Time Taken(ms): 0.447021484375
Time Taken(ms): 0.378173828125
Time Taken(ms): 0.36279296875


And here are the numbers from GraalPython
Time Taken(ms): 536.0
Time Taken(ms): 292.0
Time Taken(ms): 294.0
Time Taken(ms): 183.0
Time Taken(ms): 172.0
Time Taken(ms): 260.0
Time Taken(ms): 151.0
Time Taken(ms): 140.0
Time Taken(ms): 285.0
Time Taken(ms): 167.0

**Comment by subashatreya** [comment]
Third attempt to warm up GraalPython. I added sleep() inside the loop and made the loop run 100 times instead of 10.

```
data_dict = []
for i in range(100):
    data_dict.append({
            'name': 'User'+str(i),
            'score1': i,
            'score2': i
    })


for i in range(100):
    start = time.time() * 1000
    df = pd.DataFrame(data_dict)
    mean = df['score1'].mean()
    end = time.time() * 1000
    print("Time Taken(ms): " + str(end-start))
    time.sleep(1)

```
The numbers now are slightly better but still 100 times worse than CPython
Time Taken(ms): 16.0
Time Taken(ms): 18.0
Time Taken(ms): 19.0
Time Taken(ms): 18.0
Time Taken(ms): 17.0
Time Taken(ms): 16.0
Time Taken(ms): 19.0
Time Taken(ms): 20.0
Time Taken(ms): 18.0
Time Taken(ms): 20.0



Here are the numbers from CPython
Time Taken(ms): 0.679443359375
Time Taken(ms): 0.52490234375
Time Taken(ms): 0.4150390625
Time Taken(ms): 0.39501953125
Time Taken(ms): 0.4150390625
Time Taken(ms): 0.385009765625
Time Taken(ms): 0.447021484375
Time Taken(ms): 0.378173828125
Time Taken(ms): 0.36279296875

**Comment by timfel** [comment]
Yes, this is about what is to be expected from this benchmark. There is a lot of boundary crossing between Python code and C code. If this is truly representative of all your workload does, GraalPy has little chance of beating CPython here.

**Comment by timfel** [comment]
For reference, I modified your script as such:
```
import pandas as pd
import time

def run():
    data_dict = []
    for i in range(100):
        data_dict.append({
            'name': 'User'+str(i),
            'score1': i,
            'score2': i
        })
    df = pd.DataFrame(data_dict)
    mean = df['score1'].mean()
    return mean

total = 0
while True:
    for i in range(50):
        start = time.time() * 1000
        run()
        end = time.time() * 1000
    total += 50
    print(total, ": 50 iterations took ", end - start, "ms")
```

CPython averages around 1ms/50 iterations here for me.
GraalPy 22.3 takes quite some time to warm up. After about 7000 iterations it is pretty steady for me at ~24ms/50 iterations.
GraalPy 23.0 with our new native execution mode warms up faster, but peaks at 33ms/50 iterations after 400 iterations total.

**Comment by subashatreya** [comment]
Well, my actual application workload is a lot more complex, but I just showed this workload a simple reproducible example. 

I can try running my workload with few thousand dummy values to see if that helps it warm up. 
My requirement is not necessarily to beat CPython, but to execute one Pandas-based computation within 10ms. The number I am observing now is about 400ms.  This number must go down from 400ms to 10ms for the application to be practically viable.

Also, in this experiment, I called $JAVA_HOME/languages/python/bin/python  directly.  However, my real application is a Java-based server application running on GraalVM and Python code is embedded as Polyglot guest language. So, there is even more data conversion going from the guest Python to Host Java language.

**Comment by timfel** [comment]
If you can, I would recommend you run your actual workload with `--cpusampler` to see where time is actually spent. Then I could check if that is dominated by something we can fix or not.

**Comment by timfel** [comment]
Ah, I just found something. We actually have a deopt loop in this benchmark:
```
[Deoptimization initiated
    name: PyErr_GetExcInfo (SubstrateCompilation-6793)
    sp: 0x7ffe1e11f440  ip: 0x7f669fbec397
    reason: TransferToInterpreter  action: InvalidateReprofile
    debugId: 13  speculation: jdk.vm.ci.meta.SpeculationLog$NoSpeculationReason@c2584d3
    stack trace that triggered deoptimization:
        at com.oracle.graal.python.nodes.util.ExceptionStateNodes$GetCaughtExceptionNode.executeFromNative(ExceptionStateNodes.java:125)
        at com.oracle.graal.python.builtins.modules.cext.PythonCextErrBuiltins$PyTruffleErr_GetExcInfo.info(PythonCextErrBuiltins.java:364)
```

and 

```
[Deoptimization initiated
    name: PyTruffle_ByteArrayToNative (SubstrateCompilation-6794)
    sp: 0x7ffe1e11ea20  ip: 0x7f669fbd3b33
    reason: BoundsCheckException  action: InvalidateReprofile
    debugId: 17  speculation: jdk.vm.ci.meta.SpeculationLog$NoSpeculationReason@c2584d3
    stack trace that triggered deoptimization:
        at com.oracle.truffle.host.HostObject$ArrayGet.doByte(HostObject.java:3268)
        at com.oracle.truffle.host.HostObjectFactory$ArrayGetNodeGen$Inlined.execute(HostObjectFactory.java:473)
        at com.oracle.truffle.host.HostObject$ReadArrayElement.doArray(HostObject.java:800)
        at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.readArrayElement(HostObjectGen.java:2304)
        at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.readArrayElement(InteropLibraryGen.java:8819)
        at com.oracle.truffle.llvm.runtime.nodes.intrinsics.interop.LLVMPolyglotRead$LLVMPolyglotGetArrayElement.doIntrinsic(LLVMPolyglotRead.java:124)
```

I will try to take a look (/cc fyi @fangerer)

**Comment by timfel** [comment]
Yes, I suspect with this benchmark we won't get much better than what I had above (20-30x slower than cpython - maybe with some work it'll be 10x slower only). This particular benchmark is dominated by copying data from Python to native memory.

**Comment by subashatreya** [comment]
Thanks for the comments. Please note that when observed from Java, it was 100x slower (not just 20-30x slower) than CPython. The time for CPython was about 40ms and time from Java was about 4000ms.

Also, I could not completely understand why this benchmark is dominated by copying data from Python to native memory. The code above is calculating simple moving average (SMA) and exponential moving average (EMA) with the rolling window of 5 data points on Pandas dataframe with 100 rows.   Besides  creating dummy data and loading it up in Pandas dataframe, I don't see copying of data anywhere else in the code.

What would be the example of code that is not dominated by copying data from Python to native memory?

Anyway, let me know if there is a new build to try this again. In the meantime, I will now have to start exploring other ways to run user-supplied insecure Python code in Java server app.

**Comment by timfel** [comment]
> Also, I could not completely understand why this benchmark is dominated by copying data from Python to native memory

The calculation in this benchmark is nothing compared to loading all the data into a pandas dataframe on GraalPy. I measured the time around creating the dummy data, creating the dataframe, and then calculating the mean.

```
On GraalPy:
Creating data took: 0.0 ms
Creating data frame took: 62.00003623962402 ms
Calculating mean took 3.999948501586914 ms
1000 : 50 iterations took  2965.0 ms

On Python:
Creating data took: 0.05245208740234375 ms
Creating data frame took: 0.6833076477050781 ms
Calculating mean took 0.34689903259277344 ms
1000 : 50 iterations took  60.477294921875 ms
```

While we are indeed slower on everything involving native code here, the largest hit for us is creating the dataframe. That's because the entire data is copied into the native memory from Java, and then copied again by pandas. For CPython, they only copy from the native CPython object to pandas.

**Comment by timfel** [comment]
@vak the situation improved somewhat. Taking the [last pure python script](https://github.com/oracle/graalpython/issues/334#issuecomment-1540400217) I now see 30ms per 50 iterations on CPython and after long warmup ~200ms per iteration on GraalPy. So now around 7x slower, not 50x slower. This is still dominated by copying all the data into the pandas frame and then not calculating much with it, so I still think this is not a good benchmark. Warmup took also quite a while, i got to 200ms per 50 iterations after 4000 iterations on GraalPy, the initial ones were around 1000ms.

**Comment by fangerer** [comment]
I again looked into the performance gap. I've used a recent [CE dev build](https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/25.1.0-dev-20260616_0203/graalpy3.12-community-dev-linux-amd64.tar.gz) and ran the Python example from the [above comment](https://github.com/oracle/graalpython/issues/334#issuecomment-1540400217).

Although we did a lot of improvements since the last measurements, the performance didn't change much.
On my machine, 50 iterations take `~164.0 ms` on GraalPy and `~21.44 ms` on CPython 3.12.13.
So still something like 7x slower.

A quick profiling run showed, that we are spending most of the time in the GC.
This explains why we didn't improve because the benchmark is dominated by object allocation and cleanup.
However, I've observed that we are creating the same objects over and over (e.g. unicode object `"score1"`) and those objects immediately die. That's something we are still working on.

I also ran [the one-shot example of the first comment](https://github.com/oracle/graalpython/issues/334#issue-1700447408) in this issue and got following numbers:
```
GraalPy: 7.0 ms
CPython 3.12.13:  0.55322265625 ms
```

I think we fixed the initial _performance-is-terrible_ problem.
