### ISSUE TITLE
Exception in thread "main" ModuleNotFoundError: No module named 'whisperx'

### ISSUE THREAD

**Issue by asasas234** [oracle/graalpython#343]
I want to execute a python script through graalvm, and the error is as follows:
```
Exception in thread "main" ModuleNotFoundError: No module named 'whisperx'
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:399)
	at com.youtube.dubbing.transcription.service.WhisperXServiceImpl.main(WhisperXServiceImpl.java:37)
```
I confirmed that the script itself is fine, I can execute it normally in my python development tool, and I execute ` pip show whisperx` The output is as follows:
```
Name: whisperx
Version: 3.1.1
Summary: Time-Accurate Automatic Speech Recognition using Whisper.
Home-page: https://github.com/m-bain/whisperx
Author: Max Bain
Author-email: 
License: MIT
Location: /Users/lizhibo/miniconda3/lib/python3.10/site-packages
Requires: faster-whisper, ffmpeg-python, nltk, pandas, pyannote.audio, setuptools, torch, torchaudio, transformers
Required-by: 
```
How can I solve it?

**Comment by asasas234** [comment]
> `master`/docs/user/Packages.md

Thank you very much, for avoiding my detours, then I still consider running whisperX in the way of executing the shell in Java
