### ISSUE TITLE
Scipy install error

### ISSUE THREAD

**Issue by AigarsS** [oracle/graalpython#460]
Using` graalpy-community-jvm-24.1.1-linux-amd64` on Debian bookworm, `pip install scipy` fails with errror:
```
     Traceback (most recent call last):
        File "/workspaces/truffle-ecd/fem/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/workspaces/truffle-ecd/fem/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/workspaces/truffle-ecd/fem/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-install-dfbfp91t/scipy_9520995454f4488c8dbabaf556e9bc58/mesonpy_wrapper.py", line 79, in build_wheel
          return mesonpy.build_wheel(wheel_directory, config_settings=config_settings, metadata_directory=metadata_directory)
        File "/tmp/pip-build-env-mt3pf3y4/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 1054, in wrapper
          return func(*args, **kwargs)
        File "/tmp/pip-build-env-mt3pf3y4/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 1116, in build_wheel
          return project.wheel(out).name
        File "/tmp/pip-build-env-mt3pf3y4/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 955, in wheel
          wheel = self._wheel_builder.build(self._build_dir)
        File "/tmp/pip-build-env-mt3pf3y4/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 513, in build
          whl.writestr(f'{self.distinfo_dir}/METADATA', self._project.metadata)
        File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
          val = self.func(instance)
        File "/tmp/pip-build-env-mt3pf3y4/overlay/lib/python3.11/site-packages/mesonpy/__init__.py", line 868, in metadata
          core_metadata.headers['Version'] = [self.version]
      AttributeError: 'RFC822Message' object has no attribute 'headers'
```
Also full log attached [scipy_install.log](https://github.com/user-attachments/files/18093987/scipy_install.log)

**Comment by msimacek** [comment]
Hi @AigarsS, the build got broken by a new release of `pyproject-metadata`. I fixed it in our patch for the next release in 5f26295dc5. You should be able to work around it by installing the build dependencies manually:
```bash
pip install 'meson-python>=0.11.0,<0.13.0' 'pyproject-metadata<0.9' 'Cython>=0.29.32,<3.0' pybind11==2.10.1 pythran==0.13.1 'wheel<0.39.0' 'numpy<2'
pip install --no-build-isolation scipy
```
Or you can try a newer version, I believe `scipy==1.13.1` should work without patches.

**Comment by AigarsS** [comment]
Thank you! Proposed solution worked, was unable to install newer scipy versions (e.g 1.14.1)
