### ISSUE TITLE
[multiprocessing] AttributeError: 'module' object has no attribute 'c_char'

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#57]
```python
from multiprocessing import Process, Value, Array

def f(n, a):
    n.value = 3.1415927
    for i in range(len(a)):
        a[i] = -a[i]

if __name__ == '__main__':
    num = Value('d', 0.0)
    arr = Array('i', range(10))

    p = Process(target=f, args=(num, arr))
    p.start()
    p.join()

    print(num.value)
    print(arr[:])
```

```
Traceback (most recent call last):
  File "sharing_state_shmem.py", line 9, in <module>
    num = Value('d', 0.0)
  File "context.py", line 133, in Value
    from .sharedctypes import Value
  File "_bootstrap.py", line 1078, in __import__
  File "_bootstrap.py", line 994, in _gcd_import
  File "_bootstrap.py", line 971, in _find_and_load
  File "_bootstrap.py", line 955, in _find_and_load_unlocked
  File "_bootstrap.py", line 665, in _load_unlocked
  File "_bootstrap_external.py", line 681, in exec_module
  File "_bootstrap.py", line 219, in _call_with_frames_removed
  File "sharedctypes.py", line 26, in <module>
    'c': ctypes.c_char,  'u': ctypes.c_wchar,
AttributeError: 'module' object has no attribute 'c_char'
```

**Comment by timfel** [comment]
Thanks for the issue. Implementing `ctypes` is high on our priority list and I'm hoping to have this fixed soon. That being said, it has been high on our list for a few month now, and we are working on it, but it is a lot of work to get this right. We will update this issue once we can tell you more.

**Comment by oroppas** [comment]
Hi @timfel,

No problem. This issue needs to be resolved for graalpython to just run mx.py without error.
Of course, it's not urgent at all.

**Comment by oroppas** [comment]
Closed as implemented.
