### ISSUE TITLE
[multiprocessing] ModuleNotFoundError: No module named '_multiprocessing'

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#58]
```python
from multiprocessing import Process, Lock

def f(l, i):
    l.acquire()
    try:
        print('hello world', i)
    finally:
        l.release()

if __name__ == '__main__':
    lock = Lock()

    for num in range(10):
        Process(target=f, args=(lock, num)).start()
```

```
Traceback (most recent call last):
  File "sync_between_processes.py", line 11, in <module>
    lock = Lock()
  File "context.py", line 66, in Lock
    from .synchronize import Lock
  File "_bootstrap.py", line 1078, in __import__
  File "_bootstrap.py", line 994, in _gcd_import
  File "_bootstrap.py", line 971, in _find_and_load
  File "_bootstrap.py", line 955, in _find_and_load_unlocked
  File "_bootstrap.py", line 665, in _load_unlocked
  File "_bootstrap_external.py", line 681, in exec_module
  File "_bootstrap.py", line 219, in _call_with_frames_removed
  File "synchronize.py", line 17, in <module>
    import _multiprocessing
  File "_bootstrap.py", line 1074, in __import__
  File "_bootstrap.py", line 994, in _gcd_import
  File "_bootstrap.py", line 971, in _find_and_load
  File "_bootstrap.py", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_multiprocessing'
```

**Comment by timfel** [comment]
Hi,
thanks for the issue. We are aware of this limitation, but supporting the multiprocessing module is currently low on our priority list. I will keep this issue open, but I'm sorry to say we won't get to it soon.

**Comment by oroppas** [comment]
Hi @timfel,

Just like #57, this issue needs to be fixed so that graalpython can simply run mx.py with no error.
The priority is low.

**Comment by oroppas** [comment]
Thank you for implementing multiprocessing module! This is update:

```
Traceback (most recent call last):
  File "/run/media/ryutas/fba67dee-3fe6-4f11-980a-3e50e9a564c5/Ryuta_Data/graalpython/multiprocessing/sync_between_processes.py", line 11, in <module 'sync_between_processes.py'>
    lock = Lock()
  File "/run/media/ryutas/fba67dee-3fe6-4f11-980a-3e50e9a564c5/Ryuta_Data/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_CE_PYTHON_JAVA11/graalvm-ce-python-java11-20.0.0-dev/languages/python/lib-python/3/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/run/media/ryutas/fba67dee-3fe6-4f11-980a-3e50e9a564c5/Ryuta_Data/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_CE_PYTHON_JAVA11/graalvm-ce-python-java11-20.0.0-dev/languages/python/lib-python/3/multiprocessing/synchronize.py", line 30, in <module 'synchronize.py'>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

**Comment by oroppas** [comment]
Closed as `_multiprocessing` is implemented.
