### ISSUE TITLE
pdb requires sys.settrace

### ISSUE THREAD

**Issue by oroppas** [oracle/graalpython#63]
Hi,

I encountered the AttributeError when using pdb:

```
$ graalpython -m pdb ./setup.py test
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "<string>", line 1, in <module '<string>'>
  File "runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pdb.py", line 1724, in <module 'pdb.py'>
    pdb.main()
  File "pdb.py", line 1712, in main
    traceback.print_exc()
  File "traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "pdb.py", line 1566, in _runscript
    self.run(statement)
  File "bdb.py", line 583, in run
    sys.settrace(self.trace_dispatch)
AttributeError: 'module' object has no attribute 'settrace'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
```

**Comment by timfel** [comment]
Yes, pdb isn't supported. We recommend you use `--inspect` on the commandline and the `breakpoint()` built-in to set a breakpoint and then use the Chrome debugger for debugging
